import 'package:flutter/material.dart';

const String feedbackUrl = "https://txc.qq.com/products/691950";
const String appLandingPageUrl = "https://txc.qq.com/products/691950";
const List<Color> colors = [
  Colors.red,
  Colors.pink,
  Colors.purple,
  Colors.deepPurple,
  Colors.indigo,
  Colors.blue,
  Colors.lightBlue,
  Colors.cyan,
  Colors.teal,
  Colors.green,
  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Colors.orange,
  Colors.deepOrange,
  Colors.brown,
  Colors.grey,
  Colors.blueGrey,
  Colors.black,
];

const assetIconPathList = [
  "assets/icons/choose_asset_icon/alipay.png",
  "assets/icons/choose_asset_icon/asset-default-icon.png",
  "assets/icons/choose_asset_icon/coin.png",
  "assets/icons/choose_asset_icon/deepseek.png",
  "assets/icons/choose_asset_icon/jingdongjinrong.png",
  "assets/icons/choose_asset_icon/mastercard.png",
  "assets/icons/choose_asset_icon/octopus.png",
  "assets/icons/choose_asset_icon/ollama.png",
  "assets/icons/choose_asset_icon/paypal.png",
  "assets/icons/choose_asset_icon/duxiaoman.png",
  "assets/icons/choose_asset_icon/tiktok.png",
  "assets/icons/choose_asset_icon/baitiao.png",
  "assets/icons/choose_asset_icon/unionpay.png",
  "assets/icons/choose_asset_icon/wechat.png",
  "assets/icons/choose_asset_icon/zhihu.png",
  "assets/icons/choose_asset_icon/btc.png",
  "assets/icons/choose_asset_icon/doge.png",
  "assets/icons/choose_asset_icon/eth.png",
  "assets/icons/choose_asset_icon/usdc.png",
  "assets/icons/choose_asset_icon/usdt.png",
  "assets/icons/choose_asset_icon/e-cny.png",
  "assets/icons/choose_asset_icon/huabei.png",
  "assets/icons/choose_asset_icon/licaitong.png",
  "assets/icons/choose_asset_icon/mini-fund.png",
  "assets/icons/choose_asset_icon/yuebao.png",
  "assets/icons/choose_asset_icon/yulibao.png",
];
