name: flutter_finance_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pull_down_button: ^0.10.2
  get: ^4.6.6
  fl_chart: ^0.69.2
  settings_ui: ^2.0.2
  modal_bottom_sheet: ^3.0.0
  intl: ^0.18.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.11
  uuid: ^4.5.1
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.0
  flutter_colorpicker: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
