name: flutter_finance_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pull_down_button: ^0.10.2
  get: ^4.6.6
  fl_chart: ^0.69.2
  settings_ui: ^2.0.2
  modal_bottom_sheet: ^3.0.0
  intl: ^0.18.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.0.11
  uuid: ^4.5.1
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.0
  flutter_colorpicker: ^1.1.0
  common_utils: ^2.1.0
  flutter_screenutil: ^5.9.3
  collection: ^1.15.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: alumniSansBold
      fonts:
        - asset: assets/fonts/AlumniSans-Black.ttf
    - family: alumniSansSemiBold
      fonts:
        - asset: assets/fonts/AlumniSans-Bold.ttf
    - family: alumniSansMedium
      fonts:
        - asset: assets/fonts/AlumniSans-Medium.ttf
    - family: alumniSansRegular
      fonts:
        - asset: assets/fonts/AlumniSans-Regular.ttf

    - family: sfProBold
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
    - family: sfProSemiBold
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
    - family: sfProMedium
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
    - family: sfProRegular
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf

    - family: robotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: robotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: robotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: oswaldBold
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
    - family: oswaldSemiBold
      fonts:
        - asset: assets/fonts/Oswald-SemiBold.ttf
    - family: oswaldMedium
      fonts:
        - asset: assets/fonts/Oswald-Medium.ttf
    - family: oswaldRegular
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
